"""Phase 12 Transformation Engine — Profile Templates.

Defines standard transformation profiles for all 15+ supported output types.
Each profile specifies expected section structures, target detail levels, tone defaults,
audience defaults, citation rules, and validation guidelines.
"""

from __future__ import annotations

from typing import Dict
from .schemas import TransformationProfile


DEFAULT_PROFILES: Dict[str, TransformationProfile] = {
    "SUMMARY": TransformationProfile(
        output_type="SUMMARY",
        name="Standard Summary",
        purpose="Concise overview of core findings and key document points.",
        expected_structure=["overview", "key_findings", "conclusion"],
        required_sections=["overview", "key_findings"],
        target_length="150-300 words",
        default_tone="PROFESSIONAL",
        default_audience="GENERAL_PUBLIC",
        formatting_requirements=["Clear headings", "Bulleted key findings"],
        citation_requirements="Include inline citation references where factual claims are made.",
        validation_rules=["Must preserve all original dates and numbers", "Must not add external claims"],
        structured_json=False,
    ),
    "EXECUTIVE_SUMMARY": TransformationProfile(
        output_type="EXECUTIVE_SUMMARY",
        name="Executive Summary",
        purpose="High-level strategic briefing designed for executive leadership and decision-makers.",
        expected_structure=["executive_summary", "strategic_context", "key_takeaways", "recommendations"],
        required_sections=["executive_summary", "key_takeaways"],
        target_length="300-500 words",
        default_tone="EXECUTIVE",
        default_audience="EXECUTIVES",
        formatting_requirements=["Executive summary paragraph", "Actionable recommendations section"],
        citation_requirements="Strict inline citations mapping to source evidence.",
        validation_rules=["Highlight strategic implications", "Zero hallucinated recommendations"],
        structured_json=False,
    ),
    "QUICK_READ": TransformationProfile(
        output_type="QUICK_READ",
        name="Quick Read Snapshot",
        purpose="Fast at-a-glance bulleted snapshot for rapid consumption.",
        expected_structure=["headline", "quick_facts", "key_takeaway"],
        required_sections=["headline", "quick_facts"],
        target_length="100-200 words",
        default_tone="CONCISE",
        default_audience="GENERAL_PUBLIC",
        formatting_requirements=["Single punchy headline", "Bulleted quick facts"],
        citation_requirements="Inline citations on quick facts.",
        validation_rules=["Ultra-concise sentences", "Preserve exact numbers"],
        structured_json=False,
    ),
    "DETAILED_REPORT": TransformationProfile(
        output_type="DETAILED_REPORT",
        name="Detailed Analytical Report",
        purpose="Comprehensive, multi-section analysis covering background, evidence, and conclusions.",
        expected_structure=["title", "executive_summary", "background", "detailed_analysis", "findings", "implications", "conclusion", "references"],
        required_sections=["title", "executive_summary", "detailed_analysis", "findings"],
        target_length="800-1500 words",
        default_tone="TECHNICAL",
        default_audience="RESEARCHERS",
        formatting_requirements=["Full Markdown document structure", "Subsections with level-2 headings"],
        citation_requirements="Comprehensive inline and reference-section citations.",
        validation_rules=["Complete evidence coverage", "Factual consistency across all sections"],
        structured_json=False,
    ),
    "LINKEDIN_POST": TransformationProfile(
        output_type="LINKEDIN_POST",
        name="LinkedIn Professional Post",
        purpose="Professional social media communication engaging network connections.",
        expected_structure=["hook", "key_points", "implication", "closing"],
        required_sections=["hook", "key_points", "closing"],
        target_length="150-250 words",
        default_tone="CONVERSATIONAL",
        default_audience="GENERAL_PUBLIC",
        formatting_requirements=["Engaging opening hook", "Bullet points with emojis or symbols", "Professional closing call to action"],
        citation_requirements="Include minimal key evidence references.",
        validation_rules=["Engaging tone while preserving exact factual values", "No fabricated quotes"],
        structured_json=False,
    ),
    "X_POST": TransformationProfile(
        output_type="X_POST",
        name="X / Twitter Micro-post",
        purpose="Short-form high-impact social media post or thread starter.",
        expected_structure=["hook", "concise_facts", "conclusion"],
        required_sections=["hook", "concise_facts"],
        target_length="50-100 words",
        default_tone="CONCISE",
        default_audience="GENERAL_PUBLIC",
        formatting_requirements=["Short sentences", "Clear hashtags if relevant"],
        citation_requirements="Inline key citations.",
        validation_rules=["Strict length discipline", "Preserve core entity names and numbers"],
        structured_json=False,
    ),
    "ADVISORY": TransformationProfile(
        output_type="ADVISORY",
        name="Formal Advisory Alert",
        purpose="Official security or operational guidance alert detailing situation and action items.",
        expected_structure=["title", "executive_summary", "situation", "key_facts", "implications", "recommended_actions", "references"],
        required_sections=["title", "situation", "key_facts", "recommended_actions"],
        target_length="400-700 words",
        default_tone="FORMAL",
        default_audience="SECURITY_PROFESSIONALS",
        formatting_requirements=["Urgency indicator", "Numbered recommended actions"],
        citation_requirements="Strict inline citations for all factual situation points.",
        validation_rules=["Preserve risk levels and severity descriptors accurately"],
        structured_json=False,
    ),
    "POLICY_BRIEF": TransformationProfile(
        output_type="POLICY_BRIEF",
        name="Policy Brief",
        purpose="Objective analysis of a policy issue, relevant context, and recommended policy steps.",
        expected_structure=["issue_overview", "policy_context", "key_findings", "policy_recommendations", "references"],
        required_sections=["issue_overview", "key_findings", "policy_recommendations"],
        target_length="500-800 words",
        default_tone="FORMAL",
        default_audience="POLICYMAKERS",
        formatting_requirements=["Structured sections", "Clear policy recommendation bullets"],
        citation_requirements="Complete citations for research and policy data points.",
        validation_rules=["Unbiased factual framing", "Preserve policy constraints"],
        structured_json=False,
    ),
    "MEMO": TransformationProfile(
        output_type="MEMO",
        name="Internal Memorandum",
        purpose="Internal organizational communication to teams or stakeholders.",
        expected_structure=["header", "purpose", "context", "key_information", "action_items"],
        required_sections=["header", "purpose", "key_information"],
        target_length="250-450 words",
        default_tone="PROFESSIONAL",
        default_audience="TECHNICAL_AUDIENCE",
        formatting_requirements=["Standard MEMO header (TO, FROM, DATE, SUBJECT)", "Action items section"],
        citation_requirements="Inline citations for factual claims.",
        validation_rules=["Clear organizational focus", "Action item clarity"],
        structured_json=False,
    ),
    "ANNOUNCEMENT": TransformationProfile(
        output_type="ANNOUNCEMENT",
        name="Official Announcement",
        purpose="Official public or organizational announcement broadcasting key decisions or milestones.",
        expected_structure=["headline", "announcement_body", "key_dates_facts", "next_steps"],
        required_sections=["headline", "announcement_body", "key_dates_facts"],
        target_length="200-400 words",
        default_tone="PROFESSIONAL",
        default_audience="GENERAL_PUBLIC",
        formatting_requirements=["Clear bold headline", "Dedicated Key Dates & Facts section"],
        citation_requirements="Inline citations on milestone facts.",
        validation_rules=["Exact date preservation", "Clear entity identification"],
        structured_json=False,
    ),
    "VIDEO_SCRIPT": TransformationProfile(
        output_type="VIDEO_SCRIPT",
        name="Video Script",
        purpose="Structured multi-segment narration script for video presentations or tutorials.",
        expected_structure=["hook_intro", "segment_1_overview", "segment_2_details", "conclusion_call_to_action"],
        required_sections=["hook_intro", "segment_1_overview", "conclusion_call_to_action"],
        target_length="300-600 words",
        default_tone="EDUCATIONAL",
        default_audience="GENERAL_PUBLIC",
        formatting_requirements=["Visual/Audio cues bracketed: [Visual: ...], [Audio: ...]", "Narrator dialogue script"],
        citation_requirements="Factual claims in narration backed by citations.",
        validation_rules=["Dialogue flow", "Preserve underlying factual numbers"],
        structured_json=False,
    ),
    "PRESENTATION_OUTLINE": TransformationProfile(
        output_type="PRESENTATION_OUTLINE",
        name="Presentation Deck Outline",
        purpose="Structured slide-by-slide outline for deck generation.",
        expected_structure=["slide_1_title", "slide_2_overview", "slide_3_key_facts", "slide_4_deep_dive", "slide_5_conclusion"],
        required_sections=["slide_1_title", "slide_2_overview", "slide_3_key_facts"],
        target_length="300-500 words",
        default_tone="EXECUTIVE",
        default_audience="EXECUTIVES",
        formatting_requirements=["Slide title format: Slide N: [Title]", "Bulleted slide content and speaker notes"],
        citation_requirements="Slide notes citations.",
        validation_rules=["Logical slide progression", "Factual accuracy per slide"],
        structured_json=True,
    ),
    "INFOGRAPHIC_SPEC": TransformationProfile(
        output_type="INFOGRAPHIC_SPEC",
        name="Infographic Data Specification",
        purpose="Visual specification detailing titles, headline stats, callouts, and data points.",
        expected_structure=["main_title", "headline_stat", "data_callouts", "key_takeaways"],
        required_sections=["main_title", "headline_stat", "data_callouts"],
        target_length="200-350 words",
        default_tone="TECHNICAL",
        default_audience="GENERAL_PUBLIC",
        formatting_requirements=["Highlight metrics and stats in visual boxes", "Data visualization recommendations"],
        citation_requirements="Citations attached to every data callout stat.",
        validation_rules=["Zero altered numbers", "Stat-to-source mapping"],
        structured_json=True,
    ),
    "FAQ": TransformationProfile(
        output_type="FAQ",
        name="Frequently Asked Questions",
        purpose="Question and answer document clarifying core document concepts.",
        expected_structure=["q1_overview", "q2_details", "q3_implications"],
        required_sections=["q1_overview", "q2_details"],
        target_length="300-600 words",
        default_tone="EDUCATIONAL",
        default_audience="GENERAL_PUBLIC",
        formatting_requirements=["Q: Question format", "A: Direct factual answer"],
        citation_requirements="Inline citations within answers.",
        validation_rules=["Direct answer to each question", "Factual precision"],
        structured_json=False,
    ),
    "TRANSLATION": TransformationProfile(
        output_type="TRANSLATION",
        name="Factual Translation",
        purpose="Faithful translation from source language to target language preserving all facts.",
        expected_structure=["translated_title", "translated_content"],
        required_sections=["translated_title", "translated_content"],
        target_length="Same as source",
        default_tone="NEUTRAL",
        default_audience="GENERAL_PUBLIC",
        formatting_requirements=["Mirror original paragraph structure", "Preserve formatting markup"],
        citation_requirements="Preserve original citation tags exactly.",
        validation_rules=["Zero date/number alterations", "Zero name alterations"],
        structured_json=False,
    ),
    "EMAIL_COMMUNICATION": TransformationProfile(
        output_type="EMAIL_COMMUNICATION",
        name="Email Communication",
        purpose="Email message detailing updates, announcements, or reports.",
        expected_structure=["subject_line", "salutation", "body", "call_to_action", "sign_off"],
        required_sections=["subject_line", "salutation", "body"],
        target_length="150-300 words",
        default_tone="PROFESSIONAL",
        default_audience="GENERAL_PUBLIC",
        formatting_requirements=["Subject: line at top", "Clear salutation and sign-off"],
        citation_requirements="Inline citations where needed.",
        validation_rules=["Professional email etiquette", "Preserve facts"],
        structured_json=False,
    ),
    "STRUCTURED_REPORT": TransformationProfile(
        output_type="STRUCTURED_REPORT",
        name="Structured JSON Report",
        purpose="Machine-readable structured JSON report containing header, section list, and evidence summary.",
        expected_structure=["header", "section_list", "evidence_summary"],
        required_sections=["header", "section_list"],
        target_length="300-600 words",
        default_tone="TECHNICAL",
        default_audience="DEVELOPERS",
        formatting_requirements=["Valid JSON schema"],
        citation_requirements="Strict citation arrays per section.",
        validation_rules=["Valid JSON format", "Full evidence traceability"],
        structured_json=True,
    ),
}


__all__ = ["DEFAULT_PROFILES"]
