"""Core package: centralized configuration, logging, exceptions, constants, and schemas."""
from __future__ import annotations

from .config import Settings, get_settings
from .constants import (
    DEFAULT_APP_NAME,
    DEFAULT_PORT,
    ALLOWED_UPLOAD_EXTENSIONS,
    MIME_TYPE_MAP,
    ALL_STAGES,
    STAGE_UPLOADED,
    STAGE_VALIDATING,
    STAGE_EXTRACTING,
    STAGE_ANALYZING,
    STAGE_UCKR_READY,
    STAGE_TRANSFORMING,
    STAGE_COMPLETED,
    STAGE_FAILED,
)
from .exceptions import (
    AppException,
    DocumentValidationError,
    ExtractionError,
    ProcessingError,
    ConfigurationError,
    ResourceNotFoundError,
    UnauthorizedError,
    ForbiddenError,
    ConflictError,
    PreconditionFailedError,
)
from .logging import get_logger, setup_logging
from .schemas import (
    ApiResponse,
    HealthStatus,
    PaginationParams,
    Document,
    DocumentMetadata,
    ExtractionResult,
    ProcessingRequest,
    ProcessingResponse,
)

__all__ = [
    "Settings",
    "get_settings",
    "DEFAULT_APP_NAME",
    "DEFAULT_PORT",
    "ALLOWED_UPLOAD_EXTENSIONS",
    "MIME_TYPE_MAP",
    "ALL_STAGES",
    "STAGE_UPLOADED",
    "STAGE_VALIDATING",
    "STAGE_EXTRACTING",
    "STAGE_ANALYZING",
    "STAGE_UCKR_READY",
    "STAGE_TRANSFORMING",
    "STAGE_COMPLETED",
    "STAGE_FAILED",
    "AppException",
    "DocumentValidationError",
    "ExtractionError",
    "ProcessingError",
    "ConfigurationError",
    "ResourceNotFoundError",
    "UnauthorizedError",
    "ForbiddenError",
    "ConflictError",
    "PreconditionFailedError",
    "get_logger",
    "setup_logging",
    "ApiResponse",
    "HealthStatus",
    "PaginationParams",
    "Document",
    "DocumentMetadata",
    "ExtractionResult",
    "ProcessingRequest",
    "ProcessingResponse",
]
